/**
 * Video Service - YouTube Video Learning Assistant
 * 
 * Fetches YouTube transcripts, generates AI summaries,
 * and provides learning tools for video content.
 */

import { db } from '../db/client';
import { readHelpVideos } from '../db/schema';
import { eq, desc, and, isNull, sql } from 'drizzle-orm';
import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic();

// YouTube transcript fetching
async function fetchYouTubeTranscript(videoId: string): Promise<{
  transcript: string;
  language: string;
  source: string;
} | null> {
  try {
    // Try using youtube-transcript package or innertube API
    // For now, use a simple fetch to the timedtext API
    const response = await fetch(
      `https://www.youtube.com/watch?v=${videoId}`,
      { headers: { 'User-Agent': 'Mozilla/5.0' } }
    );
    const html = await response.text();
    
    // Extract captions URL from page
    const captionsMatch = html.match(/"captionTracks":\[(.*?)\]/);
    if (!captionsMatch) {
      console.log(`[Video Service] No captions found for ${videoId}`);
      return null;
    }
    
    const captionsData = JSON.parse(`[${captionsMatch[1]}]`);
    if (!captionsData.length) return null;
    
    // Prefer English, then auto-generated
    const englishTrack = captionsData.find((t: any) => 
      t.languageCode === 'en' || t.languageCode?.startsWith('en')
    ) || captionsData[0];
    
    if (!englishTrack?.baseUrl) return null;
    
    // Fetch the transcript
    const transcriptResponse = await fetch(englishTrack.baseUrl);
    const transcriptXml = await transcriptResponse.text();
    
    // Parse XML transcript
    const textMatches = transcriptXml.matchAll(/<text[^>]*>([^<]*)<\/text>/g);
    const lines: string[] = [];
    for (const match of textMatches) {
      const text = match[1]
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/\n/g, ' ')
        .trim();
      if (text) lines.push(text);
    }
    
    const transcript = lines.join(' ');
    const isAutoGenerated = englishTrack.kind === 'asr';
    
    return {
      transcript,
      language: englishTrack.languageCode || 'en',
      source: isAutoGenerated ? 'youtube_auto' : 'youtube_manual',
    };
  } catch (error) {
    console.error(`[Video Service] Error fetching transcript for ${videoId}:`, error);
    return null;
  }
}

// Fetch video metadata from YouTube
async function fetchYouTubeMetadata(videoId: string): Promise<{
  title: string;
  channelName: string;
  channelId: string;
  description: string;
  thumbnailUrl: string;
  durationSeconds: number;
  publishedAt: Date | null;
} | null> {
  try {
    // Use oEmbed for basic info
    const oembedResponse = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    );
    
    if (!oembedResponse.ok) return null;
    
    const oembed = await oembedResponse.json();
    
    // Try to get more info from the page
    const pageResponse = await fetch(
      `https://www.youtube.com/watch?v=${videoId}`,
      { headers: { 'User-Agent': 'Mozilla/5.0' } }
    );
    const html = await pageResponse.text();
    
    // Extract duration from page
    let durationSeconds = 0;
    const durationMatch = html.match(/"lengthSeconds":"(\d+)"/);
    if (durationMatch) {
      durationSeconds = parseInt(durationMatch[1]);
    }
    
    // Extract description
    let description = '';
    const descMatch = html.match(/"shortDescription":"([^"]+)"/);
    if (descMatch) {
      description = descMatch[1]
        .replace(/\\n/g, '\n')
        .replace(/\\"/g, '"');
    }
    
    // Extract publish date
    let publishedAt: Date | null = null;
    const dateMatch = html.match(/"publishDate":"([^"]+)"/);
    if (dateMatch) {
      publishedAt = new Date(dateMatch[1]);
    }
    
    // Extract channel ID
    let channelId = '';
    const channelIdMatch = html.match(/"channelId":"([^"]+)"/);
    if (channelIdMatch) {
      channelId = channelIdMatch[1];
    }
    
    return {
      title: oembed.title || 'Unknown Title',
      channelName: oembed.author_name || 'Unknown Channel',
      channelId,
      description,
      thumbnailUrl: oembed.thumbnail_url || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      durationSeconds,
      publishedAt,
    };
  } catch (error) {
    console.error(`[Video Service] Error fetching metadata for ${videoId}:`, error);
    return null;
  }
}

// Extract YouTube video ID from URL
export function extractYouTubeId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /youtube\.com\/v\/([a-zA-Z0-9_-]{11})/,
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

// Generate summary using Claude
async function generateSummary(
  transcript: string,
  title: string,
  length: 'short' | 'medium' | 'long'
): Promise<string> {
  const wordTargets = {
    short: 300,
    medium: 800,
    long: 1500,
  };
  
  const prompts = {
    short: `Provide a concise summary of this video transcript in about ${wordTargets.short} words. Focus on the main thesis and key takeaways.`,
    medium: `Provide a comprehensive summary of this video transcript in about ${wordTargets.medium} words. Include main arguments, key examples, and important insights.`,
    long: `Provide a detailed summary of this video transcript in about ${wordTargets.long} words. Cover all major points, examples, frameworks mentioned, and actionable insights. Use headers to organize.`,
  };
  
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 4000,
    messages: [
      {
        role: 'user',
        content: `Video Title: "${title}"\n\nTranscript:\n${transcript.slice(0, 50000)}\n\n${prompts[length]}`,
      },
    ],
  });
  
  return response.content[0].type === 'text' ? response.content[0].text : '';
}

// Extract key concepts from transcript
async function extractKeyConcepts(
  transcript: string,
  title: string
): Promise<Array<{ term: string; definition: string; context: string }>> {
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 2000,
    messages: [
      {
        role: 'user',
        content: `Video Title: "${title}"\n\nTranscript:\n${transcript.slice(0, 30000)}\n\nExtract 5-10 key concepts, terms, or frameworks discussed in this video. Return as JSON array:\n[{"term": "concept name", "definition": "brief definition", "context": "how it's used in the video"}]`,
      },
    ],
  });
  
  const text = response.content[0].type === 'text' ? response.content[0].text : '[]';
  
  try {
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    return jsonMatch ? JSON.parse(jsonMatch[0]) : [];
  } catch {
    return [];
  }
}

class VideoService {
  /**
   * Add a YouTube video for processing
   */
  async addVideo(
    url: string,
    options?: {
      canvasCourseId?: string;
      canvasModuleItemId?: string;
      canvasModuleName?: string;
      tags?: string[];
    }
  ) {
    const youtubeId = extractYouTubeId(url);
    if (!youtubeId) {
      throw new Error('Invalid YouTube URL');
    }
    
    // Check if already exists
    const existing = await db
      .select()
      .from(readHelpVideos)
      .where(eq(readHelpVideos.youtubeId, youtubeId))
      .limit(1);
    
    if (existing.length > 0) {
      return existing[0];
    }
    
    // Fetch metadata
    const metadata = await fetchYouTubeMetadata(youtubeId);
    if (!metadata) {
      throw new Error('Could not fetch video metadata');
    }
    
    // Create video record
    const [video] = await db
      .insert(readHelpVideos)
      .values({
        youtubeId,
        youtubeUrl: url,
        title: metadata.title,
        channelName: metadata.channelName,
        channelId: metadata.channelId,
        description: metadata.description,
        thumbnailUrl: metadata.thumbnailUrl,
        durationSeconds: metadata.durationSeconds,
        publishedAt: metadata.publishedAt,
        canvasCourseId: options?.canvasCourseId,
        canvasModuleItemId: options?.canvasModuleItemId,
        canvasModuleName: options?.canvasModuleName,
        tags: options?.tags,
        status: 'pending',
      })
      .returning();
    
    // Start processing in background
    this.processVideo(video.id).catch(console.error);
    
    return video;
  }
  
  /**
   * Process a video - fetch transcript and generate summaries
   */
  async processVideo(videoId: string) {
    try {
      const [video] = await db
        .select()
        .from(readHelpVideos)
        .where(eq(readHelpVideos.id, videoId))
        .limit(1);
      
      if (!video) throw new Error('Video not found');
      
      // Update status to processing
      await db
        .update(readHelpVideos)
        .set({ status: 'processing', updatedAt: new Date() })
        .where(eq(readHelpVideos.id, videoId));
      
      // Fetch transcript
      console.log(`[Video Service] Fetching transcript for ${video.youtubeId}...`);
      const transcriptData = await fetchYouTubeTranscript(video.youtubeId);
      
      if (!transcriptData) {
        await db
          .update(readHelpVideos)
          .set({
            status: 'error',
            processingError: 'Could not fetch transcript - video may not have captions',
            updatedAt: new Date(),
          })
          .where(eq(readHelpVideos.id, videoId));
        return;
      }
      
      // Update with transcript
      await db
        .update(readHelpVideos)
        .set({
          transcript: transcriptData.transcript,
          transcriptLanguage: transcriptData.language,
          transcriptSource: transcriptData.source,
          wordCount: transcriptData.transcript.split(/\s+/).length,
          updatedAt: new Date(),
        })
        .where(eq(readHelpVideos.id, videoId));
      
      // Generate summaries
      console.log(`[Video Service] Generating summaries for ${video.title}...`);
      
      const [summaryShort, summaryMedium, keyConcepts] = await Promise.all([
        generateSummary(transcriptData.transcript, video.title, 'short'),
        generateSummary(transcriptData.transcript, video.title, 'medium'),
        extractKeyConcepts(transcriptData.transcript, video.title),
      ]);
      
      // Update with summaries
      await db
        .update(readHelpVideos)
        .set({
          summaryShort,
          summaryMedium,
          keyConcepts,
          summaryGeneratedAt: new Date(),
          status: 'ready',
          updatedAt: new Date(),
        })
        .where(eq(readHelpVideos.id, videoId));
      
      console.log(`[Video Service] Completed processing ${video.title}`);
    } catch (error) {
      console.error(`[Video Service] Error processing video ${videoId}:`, error);
      await db
        .update(readHelpVideos)
        .set({
          status: 'error',
          processingError: error instanceof Error ? error.message : String(error),
          updatedAt: new Date(),
        })
        .where(eq(readHelpVideos.id, videoId));
    }
  }
  
  /**
   * Get video by ID
   */
  async getVideo(videoId: string) {
    const [video] = await db
      .select()
      .from(readHelpVideos)
      .where(eq(readHelpVideos.id, videoId))
      .limit(1);
    return video || null;
  }
  
  /**
   * Get video by YouTube ID
   */
  async getVideoByYouTubeId(youtubeId: string) {
    const [video] = await db
      .select()
      .from(readHelpVideos)
      .where(eq(readHelpVideos.youtubeId, youtubeId))
      .limit(1);
    return video || null;
  }
  
  /**
   * List videos
   */
  async listVideos(filters?: {
    canvasCourseId?: string;
    status?: string;
    archived?: boolean;
    tags?: string[];
  }) {
    let query = db.select().from(readHelpVideos);
    
    const conditions = [];
    
    if (filters?.canvasCourseId) {
      conditions.push(eq(readHelpVideos.canvasCourseId, filters.canvasCourseId));
    }
    
    if (filters?.status) {
      conditions.push(eq(readHelpVideos.status, filters.status));
    }
    
    if (filters?.archived !== undefined) {
      conditions.push(eq(readHelpVideos.isArchived, filters.archived));
    }
    
    if (conditions.length > 0) {
      query = query.where(and(...conditions)) as typeof query;
    }
    
    return query.orderBy(desc(readHelpVideos.createdAt));
  }
  
  /**
   * Get or generate summary for a video
   */
  async getSummary(videoId: string, length: 'short' | 'medium' | 'long') {
    const video = await this.getVideo(videoId);
    if (!video) throw new Error('Video not found');
    
    if (video.status !== 'ready') {
      throw new Error(`Video is ${video.status}, not ready for summary`);
    }
    
    // Check if we have cached summary
    const summaryField = length === 'short' ? 'summaryShort' 
      : length === 'medium' ? 'summaryMedium' 
      : 'summaryLong';
    
    if (video[summaryField]) {
      return { summary: video[summaryField], length, cached: true };
    }
    
    // Generate if not cached (especially for 'long')
    if (!video.transcript) {
      throw new Error('Video has no transcript');
    }
    
    const summary = await generateSummary(video.transcript, video.title, length);
    
    // Cache it
    await db
      .update(readHelpVideos)
      .set({
        [summaryField]: summary,
        summaryGeneratedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(readHelpVideos.id, videoId));
    
    return { summary, length, cached: false };
  }
  
  /**
   * Reprocess a video (refetch transcript and regenerate summaries)
   */
  async reprocessVideo(videoId: string) {
    const video = await this.getVideo(videoId);
    if (!video) throw new Error('Video not found');
    
    // Reset status
    await db
      .update(readHelpVideos)
      .set({
        status: 'pending',
        processingError: null,
        summaryShort: null,
        summaryMedium: null,
        summaryLong: null,
        keyConcepts: null,
        updatedAt: new Date(),
      })
      .where(eq(readHelpVideos.id, videoId));
    
    // Reprocess
    await this.processVideo(videoId);
    
    return this.getVideo(videoId);
  }
  
  /**
   * Delete a video
   */
  async deleteVideo(videoId: string) {
    await db.delete(readHelpVideos).where(eq(readHelpVideos.id, videoId));
  }
  
  /**
   * Update video metadata
   */
  async updateVideo(videoId: string, updates: {
    tags?: string[];
    notes?: string;
    rating?: number;
    isArchived?: boolean;
    watchProgress?: number;
  }) {
    const [updated] = await db
      .update(readHelpVideos)
      .set({
        ...updates,
        lastWatchedAt: updates.watchProgress ? new Date() : undefined,
        updatedAt: new Date(),
      })
      .where(eq(readHelpVideos.id, videoId))
      .returning();
    
    return updated;
  }
}

export const videoService = new VideoService();
